# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.9

workflows:
  test_my_app:
    jobs:
      - kubernetes-gke-publish/test
