# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.60

workflows:
  build:
    jobs:
      - kubernetes-gke-publish/test:
          context:
            - dev
